### ISSUE TITLE
还以为这个是开源的...

### ISSUE THREAD

**Issue by Jimmy-Z** [xjtuecho/uimeter#1]
点进来看才发现居然...

并不是说你应该开源, 你做的东西要不要开源你自己决定那是当然的. 可是github不是用来干这个的, 发二进制包有别的方式.

**Comment by xjtuecho** [comment]
public != open source
github是一个托管平台，能托管的不仅仅是代码，还有文档，固件，etc.
github也从来没有禁止分享二进制内容。

**Comment by myliao** [comment]
請問, 高分辨率版本可达1uA 要如何切換呢?
我按兩個鈕再上電之後，就只剩下 1A 精度
